-- +migrate Up

INSERT OR IGNORE INTO "nebula_bizapp_task_applet_meta" ("biz_app_name", "biz_app_version", "app_name", "app_version", "app_url", "st_event_type", "detect_type", "deleted", "create_time", "update_time") values ('com.sensetime.bizapp.structfpach', 10000, 'com.sensetime.algo.struct.fpach.aie', 11000, 'com.sensetime.algo.struct.fpach.aie.task', 'ST_TODO', 'structfpach_fpach_face', 0, 0, 0);
INSERT OR IGNORE INTO "nebula_bizapp_task_applet_meta" ("biz_app_name", "biz_app_version", "app_name", "app_version", "app_url", "st_event_type", "detect_type", "deleted", "create_time", "update_time") values ('com.sensetime.bizapp.structfpach', 10000, 'com.sensetime.algo.struct.fpach.aie', 11000, 'com.sensetime.algo.struct.fpach.aie.task', 'ST_TODO', 'structfpach_fpach_automobile', 0, 0, 0);
INSERT OR IGNORE INTO "nebula_bizapp_task_applet_meta" ("biz_app_name", "biz_app_version", "app_name", "app_version", "app_url", "st_event_type", "detect_type", "deleted", "create_time", "update_time") values ('com.sensetime.bizapp.structfpach', 10000, 'com.sensetime.algo.struct.fpach.aie', 11000, 'com.sensetime.algo.struct.fpach.aie.task', 'ST_TODO', 'structfpach_fpach_pedestrian', 0, 0, 0);
INSERT OR IGNORE INTO "nebula_bizapp_task_applet_meta" ("biz_app_name", "biz_app_version", "app_name", "app_version", "app_url", "st_event_type", "detect_type", "deleted", "create_time", "update_time") values ('com.sensetime.bizapp.structfpach', 10000, 'com.sensetime.algo.struct.fpach.aie', 11000, 'com.sensetime.algo.struct.fpach.aie.task', 'ST_TODO', 'structfpach_fpach_cyclist', 0, 0, 0);
INSERT OR IGNORE INTO "nebula_bizapp_task_applet_meta" ("biz_app_name", "biz_app_version", "app_name", "app_version", "app_url", "st_event_type", "detect_type", "deleted", "create_time", "update_time") values ('com.sensetime.bizapp.structfpach', 10000, 'com.sensetime.algo.struct.fpach.aie', 11000, 'com.sensetime.algo.struct.fpach.aie.task', 'ST_TODO', 'structfpach_fpach_humanpoweredvehicle', 0, 0, 0);
INSERT OR IGNORE INTO "nebula_bizapp_task_applet_meta" ("biz_app_name", "biz_app_version", "app_name", "app_version", "app_url", "st_event_type", "detect_type", "deleted", "create_time", "update_time") values ('com.sensetime.bizapp.structfpach', 10000, 'image', 0, 'image', 'ST_TODO', 'structfpach_fpach_face', 0, 0, 0);
INSERT OR IGNORE INTO "nebula_bizapp_task_applet_meta" ("biz_app_name", "biz_app_version", "app_name", "app_version", "app_url", "st_event_type", "detect_type", "deleted", "create_time", "update_time") values ('com.sensetime.bizapp.structfpach', 10000, 'image', 0, 'image', 'ST_TODO', 'structfpach_fpach_automobile', 0, 0, 0);
INSERT OR IGNORE INTO "nebula_bizapp_task_applet_meta" ("biz_app_name", "biz_app_version", "app_name", "app_version", "app_url", "st_event_type", "detect_type", "deleted", "create_time", "update_time") values ('com.sensetime.bizapp.structfpach', 10000, 'image', 0, 'image', 'ST_TODO', 'structfpach_fpach_pedestrian', 0, 0, 0);
INSERT OR IGNORE INTO "nebula_bizapp_task_applet_meta" ("biz_app_name", "biz_app_version", "app_name", "app_version", "app_url", "st_event_type", "detect_type", "deleted", "create_time", "update_time") values ('com.sensetime.bizapp.structfpach', 10000, 'image', 0, 'image', 'ST_TODO', 'structfpach_fpach_cyclist', 0, 0, 0);
INSERT OR IGNORE INTO "nebula_bizapp_task_applet_meta" ("biz_app_name", "biz_app_version", "app_name", "app_version", "app_url", "st_event_type", "detect_type", "deleted", "create_time", "update_time") values ( 'com.sensetime.bizapp.structfpach', 10000, 'image', 0, 'image', 'ST_TODO', 'structfpach_fpach_humanpoweredvehicle', 0, 0, 0);

INSERT OR IGNORE INTO "bizapp" ("name", "version", "state", "applets", "create_time", "update_time") values ('com.sensetime.bizapp.structfpach', '10000', 1, '[{"app_name":"com.sensetime.algo.struct.fpach.aie","app_version":11000,"app_url":"com.sensetime.algo.struct.fpach.aie","app_topic":"structfpach.output","target_types":[{"detect_type":"structfpach_fpach_face","st_event_type":"ST_TODO"},{"detect_type":"structfpach_fpach_automobile","st_event_type":"ST_TODO"},{"detect_type":"structfpach_fpach_pedestrian","st_event_type":"ST_TODO"},{"detect_type":"structfpach_fpach_cyclist","st_event_type":"ST_TODO"},{"detect_type":"structfpach_fpach_humanpoweredvehicle","st_event_type":"ST_TODO"}],"app_table_name":"structfpach_record"},{"app_name":"image","app_version":0,"app_url":"image","app_topic":"structfpach.output","target_types":[{"detect_type":"structfpach_fpach_face","st_event_type":"ST_TODO"},{"detect_type":"structfpach_fpach_automobile","st_event_type":"ST_TODO"},{"detect_type":"structfpach_fpach_pedestrian","st_event_type":"ST_TODO"},{"detect_type":"structfpach_fpach_cyclist","st_event_type":"ST_TODO"},{"detect_type":"structfpach_fpach_humanpoweredvehicle","st_event_type":"ST_TODO"}],"app_table_name":"structfpach_record"}]', '2022-09-08 12:56:50.966978', '2022-09-08 12:56:50.966978');

INSERT OR IGNORE INTO "bizapp_info" ("biz_app_name", "biz_app_version", "applet_infos", "create_time", "update_time") values ('com.sensetime.bizapp.structfpach', 10000, '[{"app_name":"com.sensetime.algo.struct.fpach.aie","app_version":11000,"app_url":"com.sensetime.algo.struct.fpach.aie","app_topic":"structfpach.output","target_types":[{"detect_type":"structfpach_fpach_face","st_event_type":"ST_TODO"},{"detect_type":"structfpach_fpach_automobile","st_event_type":"ST_TODO"},{"detect_type":"structfpach_fpach_pedestrian","st_event_type":"ST_TODO"},{"detect_type":"structfpach_fpach_cyclist","st_event_type":"ST_TODO"},{"detect_type":"structfpach_fpach_humanpoweredvehicle","st_event_type":"ST_TODO"}],"app_table_name":"structfpach_record"},{"app_name":"image","app_version":0,"app_url":"image","app_topic":"structfpach.output","target_types":[{"detect_type":"structfpach_fpach_face","st_event_type":"ST_TODO"},{"detect_type":"structfpach_fpach_automobile","st_event_type":"ST_TODO"},{"detect_type":"structfpach_fpach_pedestrian","st_event_type":"ST_TODO"},{"detect_type":"structfpach_fpach_cyclist","st_event_type":"ST_TODO"},{"detect_type":"structfpach_fpach_humanpoweredvehicle","st_event_type":"ST_TODO"}],"app_table_name":"structfpach_record"}]', '2022-09-08 12:55:07', '2022-09-08 12:55:07');

-- +migrate Down

